-- AlterTable
ALTER TABLE "Wallet" ALTER COLUMN "note" DROP NOT NULL,
ALTER COLUMN "note" SET DEFAULT '',
ALTER COLUMN "currency" DROP NOT NULL,
ALTER COLUMN "currency" SET DEFAULT '$',
ALTER COLUMN "initialBlance" DROP NOT NULL,
ALTER COLUMN "initialBlance" SET DEFAULT 0;
